-- Generated seed for agent_tasks and agent_events
BEGIN;
\set ON_ERROR_STOP on

-- agents
-- create 156 tasks

INSERT INTO agent_tasks (task_id, agent_name, status, input, output, duration, completed_at)
VALUES
-- values will be generated by script
;

COMMIT;
