// compute.js — Phase 4 Compute-as-a-Service routes (customer + operator).
//
// Money control points:
//   - Prices are ALWAYS generated by ComputePricingEngine from the catalog.
//   - Only SUPER_ADMIN can verify REAL payments (attestation-gated); demo
//     payments (COMPUTE_ECONOMY_DEMO_MODE) are verified by any admin and are
//     tagged SIMULATED everywhere they appear.
//   - A job runs only after its quote is PAID and its payment VERIFIED.
//   - No endpoint ever returns secrets, keys, or attestations.

import { Router } from 'express';
import prisma from '../prismaClient.js';
import { authMiddleware, requireAdmin } from '../middleware/auth.js';
import { computeQuoteLimiter, computeJobLimiter, computePaymentLimiter } from '../middleware/rateLimit.js';
import { listComputeServices, getComputeServiceBySlug } from '../services/compute/catalogService.js';
import { generateComputeQuote } from '../services/compute/pricingEngine.js';
import {
  createPaymentIntentFromQuote,
  submitPayment,
  refundPayment,
} from '../services/compute/customerPaymentMonetizer.js';
import { bookRevenueFromVerifiedPayment, getComputeEconomyOverview } from '../services/compute/revenueService.js';
import {
  createComputeJobFromAcceptedQuote,
  runComputeJob,
} from '../services/compute/jobService.js';
import { computeDemoMode } from '../services/compute/config.js';
import logger from '../utils/logger.js';

const router = Router();
const adminRouter = Router();

function handle(res, error) {
  const status = Number(error?.status) || 500;
  const message = status === 500 ? 'Compute operation failed.' : (error?.message || 'Compute operation failed.');
  if (status >= 500) logger.error('[compute] route error', error?.message);
  return res.status(status).json(status === 500 ? { error: message } : { error: message, ...(error?.payload || {}) });
}

function computeEvent(userId) {
  return (type, data) => {
    void publishCompute(userId, type, data).catch(() => {});
  };
}

async function publishCompute(userId, type, data) {
  // Real-time events are best-effort; the DB is the source of truth.
  // (Published via the shared redis client when configured.)
  const { default: redis } = await import('../redisClient.js').catch(() => ({ default: null }));
  if (!redis) return;
  await redis.publish('agentfi:compute', JSON.stringify({ type, data: { ...data, userId } })).catch(() => {});
}

// ── Customer-facing ──────────────────────────────────────────────────────────

router.get('/services', authMiddleware, async (req, res) => {
  try {
    res.json({ services: await listComputeServices(), demoMode: computeDemoMode() });
  } catch (error) {
    handle(res, error);
  }
});

// Server-priced quote + payment intent. Never accepts an amount from the body.
router.post('/quote', authMiddleware, computeQuoteLimiter, async (req, res) => {
  try {
    const serviceSlug = String(req.body?.serviceSlug || '').trim();
    const asset = String(req.body?.asset || 'BNB').toUpperCase();
    const requestText = String(req.body?.requestText || '').trim();

    const service = await getComputeServiceBySlug(serviceSlug);
    if (!service) return res.status(404).json({ error: 'Unknown service.' });

    const quoteData = await generateComputeQuote({ service, asset, userId: req.user.sub });
    const quote = await prisma.computeQuote.create({
      data: { ...quoteData, userId: req.user.sub, requestText: requestText || null },
    });
    const paymentIntent = await createPaymentIntentFromQuote({ quote });

    res.status(201).json({
      quote,
      paymentIntent,
      demoMode: computeDemoMode(),
      note: computeDemoMode()
        ? 'COMPUTE ECONOMY DEMO MODE: payment is simulated and marked SIMULATED. Verify it from the admin console.'
        : 'Server-priced quote. Real payments require SUPER_ADMIN verification with the operator attestation.',
    });
  } catch (error) {
    handle(res, error);
  }
});

// Create the DRAFT compute job for an accepted quote (binds seller/reward
// recipient). The underlying request is taken from the quote.
router.post('/jobs', authMiddleware, computeJobLimiter, async (req, res) => {
  try {
    const quoteId = String(req.body?.quoteId || '');
    if (!quoteId) return res.status(400).json({ error: 'quoteId is required' });

    const quote = await prisma.computeQuote.findUnique({ where: { id: quoteId } });
    if (!quote || quote.userId !== req.user.sub) {
      return res.status(404).json({ error: 'Quote not found.' });
    }

    const job = await createComputeJobFromAcceptedQuote({
      quoteId,
      sellerUserId: req.user.sub,
      inputText: quote.requestText || '',
    });
    res.status(201).json({ job });
  } catch (error) {
    handle(res, error);
  }
});

// Execute a monetized, verified job on the fleet. Inline scheduler: a compute
// job always completes deterministically regardless of Redis presence.
router.post('/jobs/:id/run', authMiddleware, computeJobLimiter, async (req, res) => {
  try {
    const job = await prisma.computeJob.findFirst({
      where: { id: req.params.id, sellerUserId: req.user.sub },
    });
    if (!job) return res.status(404).json({ error: 'Job not found.' });

    const result = await runComputeJob({
      job,
      publish: computeEvent(job.sellerUserId),
    });
    res.json(result);
  } catch (error) {
    handle(res, error);
  }
});

router.get('/jobs', authMiddleware, async (req, res) => {
  try {
    const jobs = await prisma.computeJob.findMany({
      where: { sellerUserId: req.user.sub },
      orderBy: { createdAt: 'desc' },
      take: Math.min(Number(req.query.take) || 50, 100),
    });
    const outputs = await prisma.computeOutput.findMany({
      where: { jobId: { in: jobs.map((j) => j.id) } },
    });
    const byJob = new Map(outputs.map((o) => [o.jobId, o]));
    res.json({ jobs: jobs.map((j) => ({ ...j, output: byJob.get(j.id) || null })) });
  } catch (error) {
    handle(res, error);
  }
});

router.get('/jobs/:id', authMiddleware, async (req, res) => {
  try {
    const job = await prisma.computeJob.findFirst({
      where: { id: req.params.id, sellerUserId: req.user.sub },
    });
    if (!job) return res.status(404).json({ error: 'Job not found.' });
    const [output, cost, revenueEvent] = await Promise.all([
      prisma.computeOutput.findUnique({ where: { jobId: job.id } }).catch(() => null),
      prisma.computeCost.findMany({ where: { jobId: job.id } }).catch(() => []),
      job.revenueEventId
        ? prisma.revenueEvent.findUnique({ where: { id: job.revenueEventId } }).catch(() => null)
        : Promise.resolve(null),
    ]);
    res.json({ job: { ...job, output, cost }, revenueEvent });
  } catch (error) {
    handle(res, error);
  }
});

router.get('/jobs/:id/output', authMiddleware, async (req, res) => {
  try {
    const job = await prisma.computeJob.findFirst({
      where: { id: req.params.id, sellerUserId: req.user.sub },
    });
    if (!job) return res.status(404).json({ error: 'Job not found.' });
    const output = await prisma.computeOutput.findUnique({ where: { jobId: job.id } });
    if (!output) return res.status(404).json({ error: 'No output yet.' });
    res.json({ resultText: output.resultText, resultHash: output.resultHash, sizeBytes: output.sizeBytes, engine: output.engine });
  } catch (error) {
    handle(res, error);
  }
});

// ── Operator (admin): payments + economy overview ────────────────────────────

adminRouter.get('/overview', authMiddleware, requireAdmin, async (req, res) => {
  try {
    res.json(await getComputeEconomyOverview());
  } catch (error) {
    handle(res, error);
  }
});

adminRouter.get('/payments', authMiddleware, requireAdmin, async (req, res) => {
  try {
    const payments = await prisma.paymentIntent.findMany({
      orderBy: { createdAt: 'desc' },
      take: Math.min(Number(req.query.take) || 100, 300),
    });
    res.json({ payments });
  } catch (error) {
    handle(res, error);
  }
});

// Record off-band payer metadata (optional; never verifies money by itself).
adminRouter.post('/payments/:id/submit', authMiddleware, requireAdmin, computePaymentLimiter, async (req, res) => {
  try {
    const intent = await submitPayment({
      paymentIntentId: req.params.id,
      payerLabel: req.body?.payerLabel,
      txHash: req.body?.txHash,
    });
    res.json({ payment: intent });
  } catch (error) {
    handle(res, error);
  }
});

// THE verification gate. Books RevenueEvent + allocations + pool funding
// atomically. Real (MANUAL_CERT) requires SUPER_ADMIN + attestation.
adminRouter.post('/payments/:id/verify', authMiddleware, requireAdmin, computePaymentLimiter, async (req, res) => {
  try {
    const result = await bookRevenueFromVerifiedPayment({
      paymentIntentId: req.params.id,
      requestedBy: req.user.sub,
      actorRole: req.userRole,
      attestation: typeof req.body?.attestation === 'string' ? req.body.attestation.trim() : null,
    });
    res.json({
      ...result,
      note: result.simulated
        ? 'SIMULATED payment verified. Figures are labeled SIMULATED and excluded from REAL revenue.'
        : 'Real external payment verified and booked as revenue.',
    });
  } catch (error) {
    handle(res, error);
  }
});

adminRouter.post('/payments/:id/refund', authMiddleware, requireAdmin, computePaymentLimiter, async (req, res) => {
  try {
    const payment = await refundPayment({
      paymentIntentId: req.params.id,
      note: req.body?.note,
    });
    res.json({ payment });
  } catch (error) {
    handle(res, error);
  }
});

export default function makeComputeRouter() {
  return { compute: router, adminCompute: adminRouter };
}